# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Roy Rivera Zamora
email: roy.fita23@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ruby on Rails Developer
baseurl: "/" # the subpath of your site, e.g. /blog
url: "royriver23.github.io" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
twitter_username: RoyRiver
github_username:  royriver23
facebook_username: royrz
stackoverflow_url: http://stackoverflow.com/users/1301469/roy-rivera-zamora
skype_username: royriver23
linkedin_url: https://www.linkedin.com/in/roy-rivera-zamora-b3a31a21?trk=hp-identity-name

# Address information
address_street: San Pedro
address_city: San José
address_state: Costa Rica
address_zip: 

# Build settings
markdown: kramdown
